### ISSUE TITLE
snackbar is not show and cannot install other version

### ISSUE THREAD

**Issue by mean-cj** [cloudlace/vuetify-dialog-promise#12]
Hello 

i use nuxt@2.11.0

after i update  vuetify-dialog-promise@2.2.2  **snackbar is not show**
and cannot downgrade version with yarn add vuetify-dialog-promise@2.1.1 or other version 

------------

frontend> yarn add cloudlace/vuetify-dialog-promise@2.1.1
yarn add v1.21.1
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/cloudlace%2fvuetify-dialog-promise: Request \"https://registry.yarnpkg.com/cloudlace%2fvuetify-dialog-promise\" returned a 405".
info If you think this is a bug, please open a bug report with the information provided in "frontend\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by brikoleur** [comment]
I don't use Nuxt or Yarn so I can't do much about this without more information. You should be able to downgrade to 2.1 with NPM however.

The change I made in 2.2 was to mount the snackbars in the component instance calling the method. I could make it so that if the snackbarParent property is set in the configuration options, then it overrides that behaviour and mounts it under the node it specifies. Do you think this would help?

**Comment by mean-cj** [comment]
Hello @brikoleur 

How i can set snackbarParent ?
```
Vue.use(VuetifyDialogPromise, {
  snackbarX: 'center',
  snackbarY: 'top',
  snackbarParent: true
})
```
thank you.

**Comment by brikoleur** [comment]
It doesn't do anything since 2.2. I'll make a new release that re-enables it, let's see if that helps. Give me a moment...

**Comment by brikoleur** [comment]
... all right, 2.2.3 is published: now you can set snackbarParent to specify the id of the node under which you want to mount the snackbars: if your v-app element's ID is "app", use: 

```
Vue.use(VuetifyDialogPromise, {
  snackbarX: 'center',
  snackbarY: 'top',
  snackbarParent: 'app'
})

```

**Comment by mean-cj** [comment]
Thank you.
